# Generated by Django 5.2.7 on 2025-11-06 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='введите название книги')),
                ('image', models.ImageField(upload_to='book/', verbose_name='загрузите фото')),
                ('description', models.TextField(verbose_name='Укажите описание книги')),
                ('director', models.CharField(default='Николай Гоголь', max_length=100, verbose_name='укажите писателя')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Мелодрамма', 'Мелодрамма'), ('Боевик', 'Боевик'), ('Классика', 'Классика')], max_length=100, verbose_name='Укажите жанр')),
                ('country', models.CharField(default='ЕВРОПА', max_length=100, verbose_name='укажите страну')),
                ('duration', models.PositiveIntegerField(default=None, verbose_name='укажите сколько страниц')),
                ('trailer', models.URLField(verbose_name='вставьте ссылку на книгу')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата добавления')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Цена кники')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=100, verbose_name='Оценка:')),
                ('comments', models.TextField(verbose_name='комментарий:')),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Книги:')),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
