# Generated by Django 5.2.7 on 2025-11-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='введите название книги')),
                ('image', models.ImageField(upload_to='book/', verbose_name='загрузите фото')),
                ('description', models.TextField(verbose_name='Укажите описание книги')),
                ('director', models.CharField(default='Николай Гоголь', max_length=100, verbose_name='укажите писателя')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Мелодрамма', 'Мелодрамма'), ('Боевик', 'Боевик'), ('Классика', 'Классика')], max_length=100, verbose_name='Укажите жанр')),
                ('country', models.CharField(default='ЕВРОПА', max_length=100, verbose_name='укажите страну')),
                ('duration', models.PositiveIntegerField(default=None, verbose_name='укажите сколько страниц')),
                ('trailer', models.URLField(verbose_name='вставьте ссылку на книгу')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
