# Generated by Django 5.2.7 on 2025-11-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratihg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите название фильма:')),
                ('description', models.TextField(verbose_name='Укажите описание фильма:')),
                ('genre', models.CharField(choices=[('фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Мелодрамма', 'Мелодрамма'), ('Боевик', 'Боевик')], max_length=100, verbose_name='Укажите жанр:')),
                ('release_date', models.DateField(verbose_name='Дата выхода фильма:')),
                ('image', models.ImageField(upload_to='films/', verbose_name='загрузите фото')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CineBoard.ratihg')),
                ('tads', models.ManyToManyField(blank=True, to='CineBoard.tag')),
            ],
        ),
    ]
