# Generated by Django 5.2.7 on 2025-11-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='tads',
            new_name='tags',
        ),
    ]
