# Generated by Django 5.2.7 on 2025-11-13 15:10

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='+996', max_length=13)),
                ('portfolio_link', models.URLField()),
                ('experience_years', models.CharField(choices=[('1-3', '1-3'), ('4-6', '4-6'), ('7-10', '7-10'), ('+10', '+10')], max_length=100)),
                ('gender_user', models.CharField(choices=[('мужкой', 'мужкой'), ('женский', 'женский')], max_length=100)),
                ('birth_data', models.DateField()),
                ('it_direction', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Fullstack', 'Fullstack'), ('Mobile', 'Mobile'), ('Devops', 'Devops'), ('Datascience', 'Datascience'), ('QA', 'QA'), ('UI/UX', 'UI/UX'), ('Cybersecurity', 'Cybersecurity'), ('Game Development', 'Game Development')], max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
