# Generated by Django 5.2.7 on 2025-11-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
