# Generated by Django 5.2.7 on 2025-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_users', '0002_rename_birth_data_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=18, max_length=100, verbose_name='лет'),
            preserve_default=False,
        ),
    ]
