# Generated by Django 5.2.7 on 2025-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LS_Waikiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caterory_clothes',
            options={'verbose_name': 'в Хэштеги', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'в Хэштеги', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='caterory_clothes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Описание продукта', verbose_name='Описание продукта:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='LS_Waikiki.caterory_clothes', verbose_name='Выбор категории:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название продукта:'),
        ),
    ]
