# Generated by Django 5.2.7 on 2025-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placing_an_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=100, verbose_name='Ваше ФИО:')),
                ('user_phone', models.IntegerField(max_length=10, verbose_name='Ваш номер телефона:')),
                ('user_city', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош'), ('Каракол', 'Каракол'), ('Джалал-Абад', 'Джалал-Абад'), ('Токмок', 'Токмок'), ('Нарын', 'Нарын'), ('Талас', 'Талас')], max_length=100, verbose_name='Ваш город:')),
                ('user_address', models.TextField(verbose_name='Ваш адрес:')),
                ('user_payment_method', models.CharField(choices=[('картой', 'картой'), ('наличкой', 'наличкой')], verbose_name='Способ оплаты:')),
                ('name_book', models.ManyToManyField(related_name='orders', to='books.book', verbose_name='Книги:')),
            ],
        ),
    ]
