# Generated by Django 5.2.7 on 2025-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASKET', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placing_an_order',
            name='user_address',
            field=models.CharField(max_length=100, verbose_name='Ваш адрес:'),
        ),
    ]
