# Generated by Django 5.2.7 on 2025-11-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASKET', '0002_alter_placing_an_order_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placing_an_order',
            options={'verbose_name': 'в Корзину', 'verbose_name_plural': 'Корзины'},
        ),
    ]
